### ISSUE TITLE
Roadmap - missing implementations

### ISSUE THREAD

**Issue by jayypluss** [jayypluss/Pokedex#1]
- [x] Tela de Listagem de Pokemóns
- [x] Tela de Detalhamento de Pokemón
  - [x] Listar mais detalhes
- [X] Documentação
- [X] Adicionar botão de voltar no detalhamento
- [X] Adicionar numeração dos Pokemóns (números/ids)
- [x] ~~Redux~~ (decidido não utilizar)
- [X] Github Action para buildar o app
- [ ] Comentários nos códigos
- [ ] Alterar fontes (layout)
